# Generated by Django 5.2.7 on 2025-12-17 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepartoPlu',
            fields=[
                ('ccom', models.CharField(blank=True, db_column='CCOM', max_length=50, null=True, verbose_name='Codice Fornitore')),
                ('descrccom', models.CharField(blank=True, db_column='DESCRCCOM', max_length=200, null=True, verbose_name='Fornitore')),
                ('rep', models.IntegerField(db_column='REP', verbose_name='Reparto')),
                ('codArticolo', models.IntegerField(db_column='codArticolo', primary_key=True, serialize=False, verbose_name='Codice Articolo')),
                ('descrizione', models.CharField(db_column='descrizione', max_length=200, verbose_name='Descrizione')),
                ('bancobilancia', models.CharField(blank=True, db_column='Bancobilancia', max_length=2, null=True, verbose_name='Banco Bilancia')),
                ('plu', models.CharField(blank=True, db_column='plu', max_length=7, null=True, verbose_name='PLU')),
                ('ean', models.CharField(blank=True, db_column='EAN', max_length=20, null=True, verbose_name='EAN')),
            ],
            options={
                'verbose_name': 'Reparto PLU',
                'verbose_name_plural': 'Reparti PLU',
                'db_table': 'V_RepartoPlu',
                'ordering': ['rep', 'codArticolo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PluAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DUPLICATO', 'PLU Duplicato'), ('MANCANTE', 'EAN Mancante'), ('INVALIDO', 'Formato Invalido')], max_length=20)),
                ('cod_articolo', models.IntegerField()),
                ('descrizione', models.TextField()),
                ('stato', models.CharField(choices=[('APERTO', 'Aperto'), ('RISOLTO', 'Risolto'), ('IGNORATO', 'Ignorato')], default='APERTO', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_risoluzione', models.DateTimeField(blank=True, null=True)),
                ('note_risoluzione', models.TextField(blank=True, null=True)),
                ('risolto_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert PLU',
                'verbose_name_plural': 'Alerts PLU',
                'db_table': 'plu_alerts',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='PluModifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_articolo', models.IntegerField(verbose_name='Codice Articolo')),
                ('campo_modificato', models.CharField(max_length=50, verbose_name='Campo')),
                ('valore_precedente', models.TextField(blank=True, null=True)),
                ('valore_nuovo', models.TextField()),
                ('data_modifica', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modifica PLU',
                'verbose_name_plural': 'Modifiche PLU',
                'db_table': 'plu_modifiche',
                'ordering': ['-data_modifica'],
            },
        ),
    ]
