# Generated by Django 5.2.7 on 2025-12-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plualert',
            name='cod_articolo',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='plumodifica',
            name='cod_articolo',
            field=models.CharField(max_length=13, verbose_name='Codice Articolo'),
        ),
    ]
