# Generated by Django 5.2.10 on 2026-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plu', '0002_alter_plualert_cod_articolo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dtaaggio', models.CharField(blank=True, db_column='dtaaggio', max_length=10, null=True)),
                ('NrReparto', models.CharField(db_column='NrReparto', max_length=13)),
                ('RepDescrizione', models.CharField(db_column='RepDescrizione', max_length=50)),
                ('DataCreazione', models.DateTimeField(blank=True, db_column='DataCreazione', null=True)),
            ],
            options={
                'verbose_name': 'Reparto',
                'verbose_name_plural': 'Reparti',
                'db_table': 't_Reparti',
                'ordering': ['NrReparto'],
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='plumodifica',
            name='utente',
        ),
        migrations.DeleteModel(
            name='PluAlert',
        ),
        migrations.DeleteModel(
            name='PluModifica',
        ),
    ]
