"""Tracciato di creazione articoli per Gold (80 colonne).

Ricavato dal file reale 808557.csv già importato con successo.
Per ogni colonna:
- nome: intestazione esatta nel CSV
- tipo: da dove arriva il valore
    "articolo" -> colonna incollata dall'utente (campo = quale)
    "testata"  -> campo comune all'infornata (campo = quale)
    "costante" -> valore fisso
    "oggi"     -> data odierna gg/mm/aaaa
    "fine"     -> 31/12/2049
    "desc20"   -> primi 20 caratteri della descrizione
    "iva"      -> aliquota IVA (sempre 22, ma resa parametrica nel form)
"""

TRACCIATO = [
    {"nome": "Barcode",                                  "tipo": "articolo", "campo": "barcode"},
    {"nome": "Descrizione principale (50car)                       ", "tipo": "articolo", "campo": "descrizione"},
    {"nome": "Descrizione breve - cassa (20car)",        "tipo": "desc20"},
    {"nome": "Struttura Merceologica",                   "tipo": "articolo",  "campo": "struttura"},
    {"nome": "Data inizio",                              "tipo": "oggi"},
    {"nome": "Data fine",                                "tipo": "fine"},
    {"nome": "Unità di stock",                           "tipo": "costante", "valore": "1"},
    {"nome": "Unità di fatturazione",                    "tipo": "costante", "valore": "1"},
    {"nome": "Iva acquisto",                             "tipo": "articolo", "campo": "iva"},
    {"nome": "Iva vendita",                              "tipo": "iva"},
    {"nome": "Unità di misura Peso/Vol",                 "tipo": "costante", "valore": "1"},
    {"nome": "Peso/vol",                                 "tipo": "costante", "valore": "1"},
    {"nome": "Unità di misura Dimensioni : CM, M,..",    "tipo": "costante", "valore": "187"},
    {"nome": "Altezza (Unità di vendita)",               "tipo": "costante", "valore": "1"},
    {"nome": "Larghezza (Unità di vendita)",             "tipo": "costante", "valore": "1"},
    {"nome": "Profondità  (Unità di vendita)",           "tipo": "costante", "valore": "1"},
    {"nome": "Tipo codice",                              "tipo": "costante", "valore": "3"},
    {"nome": "Codice logistico del collo ",              "tipo": "costante", "valore": "41"},
    {"nome": "Peso Medio pezzo",                         "tipo": "costante", "valore": "1"},
    {"nome": "Misura Peso medio pezzo",                  "tipo": "costante", "valore": "181"},
    {"nome": "Numero di pezzi per collo",                "tipo": "articolo", "campo": "pzxcrt"},
    {"nome": "Profondità  (collo)",                      "tipo": "costante", "valore": "1"},
    {"nome": "Larghezza (collo)",                        "tipo": "costante", "valore": "1"},
    {"nome": "Altezza (collo)",                          "tipo": "costante", "valore": "1"},
    {"nome": "Peso del collo",                           "tipo": "costante", "valore": "1"},
    {"nome": "Codice di movimentazione collo (ITF14)",   "tipo": "costante", "valore": ""},
    {"nome": "Codice logistico dello strato ",           "tipo": "costante", "valore": "61"},
    {"nome": "Numero Colli / Strati",                    "tipo": "costante", "valore": "1"},
    {"nome": "Altezza cm (strato)",                      "tipo": "costante", "valore": "1"},
    {"nome": "Larghezza cm (strato)",                    "tipo": "costante", "valore": "1"},
    {"nome": "Profondità cm (strato)",                   "tipo": "costante", "valore": "1"},
    {"nome": "Peso del strato",                          "tipo": "costante", "valore": "1"},
    {"nome": "Codice logistico del pallet",              "tipo": "costante", "valore": "81"},
    {"nome": "Numero Strati / pallet",                   "tipo": "costante", "valore": "1"},
    {"nome": "Altezza cm (pallet)",                      "tipo": "costante", "valore": "1"},
    {"nome": "Larghezza cm (pallet)",                    "tipo": "costante", "valore": "1"},
    {"nome": "Profondità cm (pallet)",                   "tipo": "costante", "valore": "1"},
    {"nome": "Peso del pallet",                          "tipo": "costante", "valore": "1"},
    {"nome": "Codice Imballo (supporto)",                "tipo": "costante", "valore": ""},
    {"nome": "Codice di Movimentazione ITF14",           "tipo": "costante", "valore": ""},
    {"nome": "Tipo Flusso",                              "tipo": "costante", "valore": "D"},
    {"nome": "Rete acquisto",                            "tipo": "costante", "valore": "9000"},
    {"nome": "Costo lordo (Prezzo di acquisto base)",    "tipo": "articolo", "campo": "costo"},
    {"nome": "Unit. Applic. (1/41)",                     "tipo": "costante", "valore": "1"},
    {"nome": "Valuta",                                   "tipo": "costante", "valore": "978"},
    {"nome": "Iva ACQ",                                  "tipo": "articolo", "campo": "iva"},
    {"nome": "Prezzo di vendita base",                   "tipo": "articolo", "campo": "prezzo"},
    {"nome": "Iva P.V.",                                 "tipo": "iva"},
    {"nome": "linea base",                               "tipo": "costante", "valore": "9000"},
    {"nome": "Variante logistica di riordino (1/41)",    "tipo": "costante", "valore": "1"},
    {"nome": "Referenza Fornitore  CODICE ARTICOLO",     "tipo": "articolo", "campo": "referenza"},
    {"nome": "Gruppo di Siti - default 0",               "tipo": "costante", "valore": "10001"},
    {"nome": "Codifice fornitore",                       "tipo": "testata",  "campo": "fornitore"},
    {"nome": "Filiera ",                                 "tipo": "costante", "valore": "1"},
    {"nome": "Contr. Comm",                              "tipo": "testata",  "campo": "ccom"},
    {"nome": "se Fornitore principale si di default ",   "tipo": "costante", "valore": "SI"},
    {"nome": "Multiplo di riordino  per la variante di riordino", "tipo": "costante", "valore": ""},
    {"nome": "Min di riordino a collo",                  "tipo": "costante", "valore": ""},
    {"nome": "Max di riordino a collo",                  "tipo": "costante", "valore": ""},
    {"nome": "Unità riordino",                           "tipo": "costante", "valore": "1"},
    {"nome": "Sito/RETE ",                               "tipo": "costante", "valore": "9000"},
    {"nome": "Codice Fornitore",                         "tipo": "costante", "valore": "9999"},
    {"nome": "Filiera 3",                                "tipo": "costante", "valore": "1"},
    {"nome": "Contr. Comm4 (10001) ????",                "tipo": "costante", "valore": "901"},
    {"nome": "Da rietichettare (di default NO)",         "tipo": "costante", "valore": ""},
    {"nome": "tipo consegna 0=da stock  1= XD (CROSS DOCKING)", "tipo": "costante", "valore": "0"},
    {"nome": "Codice Articolo Gold",                     "tipo": "articolo", "campo": "codgold"},
    {"nome": "Descrizione articolo per cassa lunga",     "tipo": "articolo", "campo": "descrizione"},
    {"nome": "Stato articolo ",                          "tipo": "costante", "valore": "1"},
    {"nome": "Marca - prezzo",                           "tipo": "costante", "valore": ""},
    {"nome": "Tara",                                     "tipo": "costante", "valore": ""},
    {"nome": "Data fine assortimento ordinabile",        "tipo": "fine"},
    {"nome": "Profondità assortimento vendibile",        "tipo": "costante", "valore": "10"},
    {"nome": "Tipo articolo",                            "tipo": "costante", "valore": "1"},
    {"nome": "Giorni Scandenza",                         "tipo": "costante", "valore": ""},
    {"nome": "Peso (Sottoimballo)            ",          "tipo": "costante", "valore": ""},
    {"nome": "Altezza cm (sottoimballo)        ",        "tipo": "costante", "valore": ""},
    {"nome": "Larghezza cm (sottoimballo)      ",        "tipo": "costante", "valore": ""},
    {"nome": "Profondita cm (sottoimballo)     ",        "tipo": "costante", "valore": ""},
    {"nome": "C    ",                                    "tipo": "costante", "valore": ""},
]