# Generated by Django 5.2.10 on 2026-02-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attivita',
        ),
    ]
