# Generated by Django 5.2.10 on 2026-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Attività',
                'verbose_name_plural': 'Attività',
                'db_table': 'shared.attivita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merchandiser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cognome', models.CharField(max_length=255)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchandiser',
                'verbose_name_plural': 'Merchandiser',
                'db_table': 'shared.merchandiser',
                'ordering': ['cognome', 'nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('lun', models.BooleanField(default=False)),
                ('mar', models.BooleanField(default=False)),
                ('mer', models.BooleanField(default=False)),
                ('gio', models.BooleanField(default=False)),
                ('ven', models.BooleanField(default=False)),
                ('sab', models.BooleanField(default=False)),
                ('dom', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('badge', models.CharField(blank=True, max_length=10, null=True)),
                ('plafond_ore', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attivo', models.BooleanField(default=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slot',
                'db_table': 'shared.slot',
                'ordering': ['-data_inizio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlotFornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fornitore_id', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Slot Fornitore',
                'verbose_name_plural': 'Slot Fornitori',
                'db_table': 'shared.slot_fornitori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlotIngressoUscita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ingresso_1', models.TimeField(blank=True, null=True)),
                ('uscita_1', models.TimeField(blank=True, null=True)),
                ('ingresso_2', models.TimeField(blank=True, null=True)),
                ('uscita_2', models.TimeField(blank=True, null=True)),
                ('ingresso_extra', models.TimeField(blank=True, null=True)),
                ('uscita_extra', models.TimeField(blank=True, null=True)),
                ('forzato', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Ingresso/Uscita',
                'verbose_name_plural': 'Ingressi/Uscite',
                'db_table': 'shared.slot_ingressi_uscite',
                'ordering': ['data'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SottoReparto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codice', models.CharField(max_length=5)),
                ('descrizione', models.CharField(max_length=50)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sotto Reparto',
                'verbose_name_plural': 'Sotto Reparti',
                'db_table': 'shared.sotto_reparti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cognome', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('code_reparto', models.CharField(blank=True, max_length=5, null=True)),
                ('code_sotto_reparto', models.CharField(blank=True, max_length=5, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
                'db_table': 'shared.utenti',
                'managed': False,
            },
        ),
    ]
