# Generated by Django 5.2.10 on 2026-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='Username')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome visualizzato')),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Ultima attività')),
                ('last_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Ultima pagina visitata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Indirizzo IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User Agent')),
                ('environment', models.CharField(db_index=True, default='dev', max_length=10, verbose_name='Ambiente')),
            ],
            options={
                'verbose_name': 'Attività utente',
                'verbose_name_plural': 'Attività utenti',
                'db_table': 'shared.user_activity',
                'ordering': ['-last_activity'],
                'unique_together': {('username', 'environment')},
            },
        ),
    ]
