# Generated by Django 5.2.10 on 2026-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenzia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=50)),
                ('nota', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Agenzie',
                'db_table': 'shared.agenzie',
                'ordering': ['descrizione'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssegnazionePallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dettaglio', models.CharField(blank=True, max_length=100, null=True)),
                ('nota', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_estesa', models.CharField(blank=True, max_length=255, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
                ('modificato_da', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Assegnazioni Pallet',
                'db_table': 'shared.assegnazioni_pallet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssegnazioneTestata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mese', models.SmallIntegerField()),
                ('anno', models.SmallIntegerField()),
                ('nota_testata', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_atelier', models.CharField(blank=True, max_length=50, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
                ('modificato_da', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Assegnazioni Testate',
                'db_table': 'shared.assegnazioni_testate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Banchi',
                'db_table': 'shared.banchi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nominativo', models.CharField(max_length=50)),
                ('codice_as400', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Buyer',
                'db_table': 'shared.buyer',
                'ordering': ['nominativo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('codice', models.IntegerField(db_column='codice', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=50)),
                ('buyer', models.CharField(blank=True, max_length=16, null=True)),
                ('reparto', models.CharField(blank=True, max_length=13, null=True)),
                ('codice_commerciale', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fornitori',
                'db_table': 'shared.fornitori',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hostess',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nominativo', models.CharField(max_length=50)),
                ('ruolo', models.CharField(blank=True, max_length=30, null=True)),
                ('nota', models.CharField(blank=True, max_length=100, null=True)),
                ('scadenza_libretto_sanitario', models.DateField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Hostess',
                'db_table': 'shared.hostess',
                'ordering': ['nominativo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codice', models.CharField(max_length=10, unique=True)),
                ('coord_x', models.IntegerField(default=0)),
                ('coord_y', models.IntegerField(default=0)),
                ('dimensione', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pallet',
                'db_table': 'shared.pallet',
                'ordering': ['codice'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codice', models.CharField(max_length=10, unique=True)),
                ('codice_promozione', models.IntegerField()),
                ('descrizione', models.CharField(max_length=100)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('anno', models.IntegerField()),
                ('num_hostess', models.SmallIntegerField(default=8)),
            ],
            options={
                'verbose_name_plural': 'Periodi',
                'db_table': 'shared.periodi',
                'ordering': ['-data_inizio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PianificazioneHostess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('giorno', models.DateField()),
                ('slot', models.SmallIntegerField()),
                ('nota', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pianificazioni Hostess',
                'db_table': 'shared.pianificazione_hostess',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PresenzaHostess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('giorno', models.DateField()),
                ('slot', models.SmallIntegerField()),
                ('tipo', models.CharField(choices=[('STD', 'Standard'), ('FAB', 'Fabbrica/Fornitore')], default='STD', max_length=3)),
                ('ingresso_mattino', models.TimeField(blank=True, null=True)),
                ('uscita_mattino', models.TimeField(blank=True, null=True)),
                ('ingresso_pomeriggio', models.TimeField(blank=True, null=True)),
                ('uscita_pomeriggio', models.TimeField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_fornitore', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Presenze Hostess',
                'db_table': 'shared.presenze_hostess',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Reparti',
                'db_table': 'shared.reparti',
                'ordering': ['descrizione'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('locazione', models.CharField(max_length=50)),
                ('bloccata', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Testate',
                'db_table': 'shared.testate',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtenteBuyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username_ad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Utenti Buyer',
                'db_table': 'shared.utenti_buyer',
                'managed': False,
            },
        ),
    ]
