# Generated by Django 5.2.7 on 2026-10-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(choices=[('MB', 'Monte Bianco'), ('CE', 'Cervino')], max_length=2)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('azienda', models.CharField(max_length=100)),
                ('data_arrivo', models.DateField()),
                ('data_partenza', models.DateField()),
                ('note', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'prenotazione',
                'verbose_name_plural': 'prenotazioni',
                'ordering': ['data_arrivo'],
            },
        ),
    ]
