# Generated by Django 5.2.7 on 2025-12-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nome file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Caricato il')),
                ('raw_content', models.TextField(verbose_name='Contenuto originale')),
            ],
        ),
        migrations.CreateModel(
            name='GoldTableSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_table'], name='importelab__source__c937fe_idx'), models.Index(fields=['synced_at'], name='importelab__synced__344462_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='Numero riga')),
                ('raw_line', models.TextField(verbose_name='Riga originale')),
                ('cod_art_fo', models.CharField(blank=True, max_length=50, verbose_name='CodArtFo')),
                ('descrizione_articolo', models.CharField(blank=True, max_length=255, verbose_name='Descrizione articolo')),
                ('iva', models.IntegerField(blank=True, null=True, verbose_name='IVA')),
                ('prz_acq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='PrzAcq')),
                ('campo5', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Campo5')),
                ('pz_x_crt', models.IntegerField(blank=True, null=True, verbose_name='PzXCrt')),
                ('crt_x_str', models.IntegerField(blank=True, null=True, verbose_name='CrtXstr')),
                ('str_x_plt', models.IntegerField(blank=True, null=True, verbose_name='StrXplt')),
                ('tot_colli', models.IntegerField(blank=True, null=True, verbose_name='TotColli')),
                ('ean', models.CharField(blank=True, max_length=32, verbose_name='EAN')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='importelab.importbatch', verbose_name='Import')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
    ]
