# Generated by ChatGPT on 2025-12-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importelab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateAggPrAcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dta_aggio', models.CharField(blank=True, max_length=32)),
                ('cod_art_fo', models.CharField(blank=True, max_length=50)),
                ('codart', models.CharField(blank=True, max_length=50)),
                ('descrart', models.CharField(blank=True, max_length=255)),
                ('stato', models.CharField(blank=True, max_length=32)),
                ('cidac_prezzo', models.CharField(blank=True, max_length=64)),
                ('az', models.CharField(blank=True, default='Agg', max_length=8)),
                ('ros_pracq', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sett', models.CharField(blank=True, max_length=32)),
                ('rep', models.CharField(blank=True, max_length=32)),
                ('srep', models.CharField(blank=True, max_length=32)),
                ('ccom', models.CharField(blank=True, max_length=32)),
                ('descrccom', models.CharField(blank=True, max_length=255)),
                ('ros_iva', models.IntegerField(blank=True, null=True)),
                ('cidac_iva', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_agg_pracq', to='importelab.importbatch', verbose_name='Batch')),
            ],
            options={
                'ordering': ['rep', 'srep', 'ccom', 'cod_art_fo'],
            },
        ),
        migrations.CreateModel(
            name='IntermediateAggiornaEan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_art_fo', models.CharField(blank=True, max_length=50)),
                ('descrizione_articolo', models.CharField(blank=True, max_length=255)),
                ('ean', models.CharField(blank=True, max_length=32)),
                ('codart', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_aggiorna_ean', to='importelab.importbatch', verbose_name='Batch')),
            ],
            options={
                'ordering': ['descrizione_articolo', 'cod_art_fo'],
            },
        ),
        migrations.CreateModel(
            name='IntermediateAggiornamentiVari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_art_fo', models.CharField(blank=True, max_length=50)),
                ('codart', models.CharField(blank=True, max_length=50)),
                ('descrizione_articolo', models.CharField(blank=True, max_length=255)),
                ('ean', models.CharField(blank=True, max_length=32)),
                ('cidac_pz_x_crt', models.IntegerField(blank=True, null=True)),
                ('agg_pz_x_crt', models.CharField(blank=True, max_length=8)),
                ('r_pz_x_crt', models.IntegerField(blank=True, null=True)),
                ('cidac_crt_x_str', models.IntegerField(blank=True, null=True)),
                ('agg_crt_x_str', models.CharField(blank=True, max_length=8)),
                ('r_crt_x_str', models.IntegerField(blank=True, null=True)),
                ('r_str_x_plt', models.IntegerField(blank=True, null=True)),
                ('cidac_str_x_plt', models.IntegerField(blank=True, null=True)),
                ('agg_str_x_plt', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_agg_var', to='importelab.importbatch', verbose_name='Batch')),
            ],
            options={
                'ordering': ['cod_art_fo'],
            },
        ),
        migrations.AddIndex(
            model_name='intermediateaggpracq',
            index=models.Index(fields=['batch', 'cod_art_fo'], name='importelab__batch_i_7e0ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='intermediateaggiornaean',
            index=models.Index(fields=['batch', 'ean'], name='importelab__batch_i_ef4a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='intermediateaggiornaean',
            index=models.Index(fields=['batch', 'cod_art_fo'], name='importelab__batch_i_ba4952_idx'),
        ),
        migrations.AddIndex(
            model_name='intermediateaggiornamentivari',
            index=models.Index(fields=['batch', 'cod_art_fo'], name='importelab__batch_i_4e0e1e_idx'),
        ),
    ]
