# Generated by Django 5.2.7 on 2026-01-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importelab', '0003_importbatch_add_import_dir'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='intermediateaggiornaean',
            new_name='importelab__batch_i_101e7a_idx',
            old_name='importelab__batch_i_ef4a7d_idx',
        ),
        migrations.RenameIndex(
            model_name='intermediateaggiornaean',
            new_name='importelab__batch_i_8b45e5_idx',
            old_name='importelab__batch_i_ba4952_idx',
        ),
        migrations.RenameIndex(
            model_name='intermediateaggiornamentivari',
            new_name='importelab__batch_i_e4c750_idx',
            old_name='importelab__batch_i_4e0e1e_idx',
        ),
        migrations.RenameIndex(
            model_name='intermediateaggpracq',
            new_name='importelab__batch_i_4a5bc4_idx',
            old_name='importelab__batch_i_7e0ce0_idx',
        ),
    ]
