# Generated by Django 5.2.7 on 2026-04-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSessione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piano_gold', models.CharField(max_length=50)),
                ('inizio_sellout', models.DateField(blank=True, null=True)),
                ('titolo', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('pubblicata', 'Pubblicata')], default='bozza', max_length=20)),
                ('creato_da', models.CharField(max_length=100)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sessione Promo',
                'verbose_name_plural': 'Sessioni Promo',
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='PromoSessioneRiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_art', models.CharField(blank=True, max_length=50)),
                ('desc_art', models.CharField(blank=True, max_length=200)),
                ('cod_forn', models.CharField(blank=True, max_length=50)),
                ('desc_forn', models.CharField(blank=True, max_length=200)),
                ('giac_pdv', models.BigIntegerField(blank=True, null=True)),
                ('giac_dep', models.BigIntegerField(blank=True, null=True)),
                ('cod_art_expo', models.CharField(blank=True, max_length=50)),
                ('desc_expo', models.CharField(blank=True, max_length=200)),
                ('ordine_in_corso', models.CharField(blank=True, max_length=100)),
                ('data_consegna', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('neutro', 'Neutro'), ('incluso', 'Incluso'), ('escluso', 'Escluso')], default='neutro', max_length=20)),
                ('nota', models.CharField(blank=True, max_length=500)),
                ('aggiunta_manuale', models.BooleanField(default=False)),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='piano_promo.promosessione')),
            ],
            options={
                'ordering': ['cod_forn', 'cod_art'],
            },
        ),
    ]
