# Generated by Django 5.2 on 2026-05-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_promo', '0003_promosessione_query_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promosessione',
            name='stato',
        ),
        migrations.AlterField(
            model_name='promosessioneriga',
            name='stato',
            field=models.CharField(choices=[('neutro', 'Neutro'), ('incluso', 'Ordinato'), ('escluso', 'Da Ordinare')], default='neutro', max_length=20),
        ),
    ]
