# Generated by Django 5.2.7 on 2026-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_promo', '0004_remove_promosessione_stato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promosessioneriga',
            name='prezzo_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
