# Generated by Django 5.2.7 on 2026-05-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_promo', '0005_prezzo_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promosessione',
            name='piano_gold',
            field=models.CharField(max_length=500),
        ),
    ]
