# Generated by Django 5.2.7 on 2026-06-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piano_promo', '0006_piano_gold_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promosessioneriga',
            options={'ordering': ['cod_piano_gold', 'desc_forn', 'cod_art', 'cod_art_expo']},
        ),
    ]
