# Generated by Django 5.2.10 on 2026-02-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggiornaAttri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodArticolo', models.CharField(blank=True, default='', max_length=50)),
                ('ClasseAttri', models.CharField(blank=True, default='', max_length=50)),
                ('CodAttri', models.CharField(blank=True, default='', max_length=10)),
                ('ValoreNum', models.CharField(blank=True, default='', max_length=50)),
                ('ValoreAlpha', models.CharField(blank=True, default='', max_length=255)),
                ('ValoreData', models.CharField(blank=True, default='', max_length=50)),
                ('dtaini', models.DateTimeField(blank=True, null=True)),
                ('dtaFine', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Aggiorna Attributo',
                'verbose_name_plural': 'Aggiorna Attributi',
                'db_table': 'scaricopromo_aggiornaattri',
            },
        ),
        migrations.CreateModel(
            name='ApriAttri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodArticolo', models.CharField(blank=True, default='', max_length=50)),
                ('ClasseAttri', models.CharField(blank=True, default='', max_length=50)),
                ('CodAttri', models.CharField(blank=True, default='', max_length=10)),
                ('ValoreNum', models.CharField(blank=True, default='', max_length=50)),
                ('ValoreAlpha', models.CharField(blank=True, default='', max_length=255)),
                ('ValoreData', models.CharField(blank=True, default='', max_length=50)),
                ('dtaini', models.DateTimeField(blank=True, null=True)),
                ('dtaFine', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Apri Attributo',
                'verbose_name_plural': 'Apri Attributi',
                'db_table': 'scaricopromo_apriattri',
            },
        ),
        migrations.CreateModel(
            name='ChiudiAttri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodArticolo', models.CharField(blank=True, default='', max_length=50)),
                ('ClasseAttri', models.CharField(blank=True, default='', max_length=50)),
                ('CodAttri', models.CharField(blank=True, default='', max_length=10)),
                ('ValoreNum', models.CharField(blank=True, default='', max_length=50)),
                ('ValoreAlpha', models.CharField(blank=True, default='', max_length=255)),
                ('ValoreData', models.CharField(blank=True, default='', max_length=50)),
                ('DtaIniz', models.CharField(blank=True, default='', max_length=50)),
                ('DTACH', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Chiudi Attributo',
                'verbose_name_plural': 'Chiudi Attributi',
                'db_table': 'scaricopromo_chiudiattri',
            },
        ),
        migrations.CreateModel(
            name='MettereInA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codart', models.CharField(blank=True, default='', max_length=50, verbose_name='Codice Articolo')),
                ('ccom', models.CharField(blank=True, default='', max_length=50, verbose_name='Codice Commerciale')),
            ],
            options={
                'verbose_name': 'Mettere in A',
                'verbose_name_plural': 'Mettere in A',
                'db_table': 'scaricopromo_metterein_a',
            },
        ),
        migrations.CreateModel(
            name='MettereInE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codart', models.CharField(blank=True, default='', max_length=50, verbose_name='Codice Articolo')),
            ],
            options={
                'verbose_name': 'Mettere in E',
                'verbose_name_plural': 'Mettere in E',
                'db_table': 'scaricopromo_metterein_e',
            },
        ),
        migrations.CreateModel(
            name='MettereInF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codart', models.CharField(blank=True, default='', max_length=50, verbose_name='Codice Articolo')),
            ],
            options={
                'verbose_name': 'Mettere in F',
                'verbose_name_plural': 'Mettere in F',
                'db_table': 'scaricopromo_metterein_f',
            },
        ),
        migrations.CreateModel(
            name='MettereInI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codart', models.CharField(blank=True, default='', max_length=50, verbose_name='Codice Articolo')),
                ('ccom', models.CharField(blank=True, default='', max_length=50, verbose_name='Codice Commerciale')),
            ],
            options={
                'verbose_name': 'Mettere in I',
                'verbose_name_plural': 'Mettere in I',
                'db_table': 'scaricopromo_metterein_i',
            },
        ),
        migrations.CreateModel(
            name='MettereInK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codart', models.CharField(blank=True, default='', max_length=50, verbose_name='Codice Articolo')),
            ],
            options={
                'verbose_name': 'Mettere in K',
                'verbose_name_plural': 'Mettere in K',
                'db_table': 'scaricopromo_metterein_k',
            },
        ),
        migrations.CreateModel(
            name='MettereInS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codart', models.CharField(blank=True, default='', max_length=50, verbose_name='Codice Articolo')),
            ],
            options={
                'verbose_name': 'Mettere in S',
                'verbose_name_plural': 'Mettere in S',
                'db_table': 'scaricopromo_metterein_s',
            },
        ),
        migrations.CreateModel(
            name='NonPossoMettereInA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codart', models.CharField(blank=True, default='', max_length=50, verbose_name='Codice Articolo')),
                ('ccom', models.CharField(blank=True, default='', max_length=50, verbose_name='Codice Commerciale')),
            ],
            options={
                'verbose_name': 'Non posso mettere in A',
                'verbose_name_plural': 'Non posso mettere in A',
                'db_table': 'scaricopromo_nonposso_a',
            },
        ),
        migrations.CreateModel(
            name='PerExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Promozioni', models.CharField(blank=True, default='', max_length=255)),
                ('FornitoreAmministrativo', models.CharField(blank=True, default='', max_length=255)),
                ('ContrattoCommerciale', models.CharField(blank=True, default='', max_length=255)),
                ('RagioneSociale', models.CharField(blank=True, default='', max_length=255)),
                ('CodiceProdotto', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('DescrizioneProdotto', models.CharField(blank=True, default='', max_length=255)),
                ('SelezionePromozione', models.CharField(blank=True, default='', max_length=255)),
                ('DataInizio', models.CharField(blank=True, default='', max_length=50)),
                ('DataFine', models.CharField(blank=True, default='', max_length=50)),
                ('ScontoExtra', models.CharField(blank=True, default='', max_length=50)),
                ('TipoSconto1', models.CharField(blank=True, default='', max_length=50)),
                ('TipoSconto', models.CharField(blank=True, default='', max_length=50)),
                ('Meccanica', models.CharField(blank=True, default='', max_length=50)),
                ('Meccanicav', models.CharField(blank=True, default='', max_length=50)),
                ('Valore', models.CharField(blank=True, default='', max_length=50)),
                ('Valore1', models.CharField(blank=True, default='', max_length=50)),
                ('export', models.CharField(blank=True, default='', max_length=50)),
                ('QtaOmaggio', models.CharField(blank=True, default='', max_length=50)),
                ('pianoB', models.CharField(blank=True, default='', max_length=50)),
                ('vl', models.CharField(blank=True, default='', max_length=50, verbose_name='Variante Logistica')),
                ('DATAEXPORT', models.CharField(blank=True, default='', max_length=50)),
                ('utenteWind', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Export Promozione',
                'verbose_name_plural': 'Export Promozioni',
                'db_table': 'scaricopromo_perexport',
            },
        ),
        migrations.CreateModel(
            name='PerExportStorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Promozioni', models.CharField(blank=True, default='', max_length=255)),
                ('FornitoreAmministrativo', models.CharField(blank=True, default='', max_length=255)),
                ('ContrattoCommerciale', models.CharField(blank=True, default='', max_length=255)),
                ('RagioneSociale', models.CharField(blank=True, default='', max_length=255)),
                ('CodiceProdotto', models.CharField(blank=True, default='', max_length=50)),
                ('DescrizioneProdotto', models.CharField(blank=True, default='', max_length=255)),
                ('SelezionePromozione', models.CharField(blank=True, default='', max_length=255)),
                ('DataInizio', models.CharField(blank=True, default='', max_length=50)),
                ('DataFine', models.CharField(blank=True, default='', max_length=50)),
                ('ScontoExtra', models.CharField(blank=True, default='', max_length=50)),
                ('TipoSconto1', models.CharField(blank=True, default='', max_length=50)),
                ('TipoSconto', models.CharField(blank=True, default='', max_length=50)),
                ('Meccanica', models.CharField(blank=True, default='', max_length=50)),
                ('Meccanicav', models.CharField(blank=True, default='', max_length=50)),
                ('Valore', models.CharField(blank=True, default='', max_length=50)),
                ('Valore1', models.CharField(blank=True, default='', max_length=50)),
                ('export', models.CharField(blank=True, default='', max_length=50)),
                ('QtaOmaggio', models.CharField(blank=True, default='', max_length=50)),
                ('pianoB', models.CharField(blank=True, default='', max_length=50)),
                ('VL', models.CharField(blank=True, default='', max_length=50)),
                ('DATAEXPORT', models.CharField(blank=True, default='', max_length=50)),
                ('utenteWind', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Export Storico',
                'verbose_name_plural': 'Export Storici',
                'db_table': 'scaricopromo_perexport_storico',
            },
        ),
    ]
