# Generated by Django 5.2.7 on 2026-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaricopromo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggiornaattri',
            name='dtaini',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='apriattri',
            name='dtaini',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
