# Generated by Django 5.2.7 on 2026-03-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaricopromo', '0002_alter_aggiornaattri_dtaini_alter_apriattri_dtaini'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtDaVerificare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Promozioni', models.CharField(blank=True, default='', max_length=255)),
                ('FornitoreAmministrativo', models.CharField(blank=True, default='', max_length=255)),
                ('ContrattoCommerciale', models.CharField(blank=True, default='', max_length=255)),
                ('RagioneSociale', models.CharField(blank=True, default='', max_length=255)),
                ('CodiceProdotto', models.CharField(blank=True, default='', max_length=50)),
                ('DescrizioneProdotto', models.CharField(blank=True, default='', max_length=255)),
                ('SelezionePromozione', models.CharField(blank=True, default='', max_length=255)),
                ('DataInizio', models.CharField(blank=True, default='', max_length=50)),
                ('DataFine', models.CharField(blank=True, default='', max_length=50)),
                ('ScontoExtra', models.CharField(blank=True, default='', max_length=50)),
                ('TipoSconto1', models.CharField(blank=True, default='', max_length=50)),
                ('TipoSconto', models.CharField(blank=True, default='', max_length=50)),
                ('Meccanica', models.CharField(blank=True, default='', max_length=50)),
                ('Meccanicav', models.CharField(blank=True, default='', max_length=255)),
                ('Valore', models.CharField(blank=True, default='', max_length=50)),
                ('Valore1', models.CharField(blank=True, default='', max_length=50)),
                ('export', models.CharField(blank=True, default='', max_length=50)),
                ('QtaOmaggio', models.CharField(blank=True, default='', max_length=50)),
                ('VL', models.CharField(blank=True, default='', max_length=50)),
                ('promor', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Articolo da Verificare',
                'verbose_name_plural': 'Articoli da Verificare',
                'db_table': 'scaricopromo.artdaverificare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtFreFase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOBCEXT', models.CharField(blank=True, default='', max_length=26, verbose_name='Reparto')),
                ('TSOBDESC', models.CharField(blank=True, default='', max_length=100, verbose_name='Desc Reparto')),
                ('CNUM', models.CharField(blank=True, default='', max_length=255, verbose_name='Cod Fornitore')),
                ('CNUF', models.CharField(blank=True, default='', max_length=255, verbose_name='CCOM')),
                ('DESC_CNUF', models.CharField(blank=True, default='', max_length=255, verbose_name='Desc CCOM')),
                ('ARTFO', models.CharField(blank=True, default='', max_length=40, verbose_name='Cod Art Fornitore')),
                ('CEXR', models.CharField(blank=True, db_index=True, default='', max_length=26, verbose_name='Cod Articolo')),
                ('DESC_CEXR', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrizione')),
                ('PrezzoVOff', models.CharField(blank=True, default='', max_length=50, verbose_name='Prezzo Offerta')),
                ('VL', models.CharField(blank=True, default='', max_length=10, verbose_name='Variante Logistica')),
                ('TIPO_RIORDINO', models.CharField(blank=True, default='', max_length=255, verbose_name='Tipo Riordino')),
                ('LINEA_PRODOTTO', models.CharField(blank=True, default='', max_length=255, verbose_name='Linea Prodotto')),
                ('Desc_Linea', models.CharField(blank=True, default='', max_length=255, verbose_name='Desc Linea')),
                ('PrezzoV', models.CharField(blank=True, default='', max_length=50, verbose_name='Prezzo Vendita')),
                ('STATO', models.CharField(blank=True, default='', max_length=16, verbose_name='Stato')),
                ('scelta', models.BooleanField(default=False, verbose_name='Selezionato')),
                ('ok', models.CharField(blank=True, default='', max_length=10)),
                ('SOBCINT', models.CharField(blank=True, default='', max_length=26)),
            ],
            options={
                'verbose_name': 'Articolo Fase 1',
                'verbose_name_plural': 'Articoli Fase 1',
                'db_table': 'scaricopromo.artfrefase1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodArtPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodArt', models.CharField(blank=True, default='', max_length=50)),
                ('stato', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Cod Art Promo',
                'verbose_name_plural': 'Cod Art Promo',
                'db_table': 'scaricopromo.codartpromo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportaArticoliPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REP', models.CharField(blank=True, default='', max_length=26)),
                ('CODFORN', models.CharField(blank=True, default='', max_length=255)),
                ('CCOM', models.CharField(blank=True, default='', max_length=255)),
                ('DESCRCCOM', models.CharField(blank=True, default='', max_length=255)),
                ('CODARTFO', models.CharField(blank=True, default='', max_length=40)),
                ('CODART', models.CharField(blank=True, db_index=True, default='', max_length=26)),
                ('DESCRART', models.CharField(blank=True, default='', max_length=255)),
                ('S', models.CharField(blank=True, default='', max_length=16)),
                ('TCOL', models.CharField(blank=True, default='', max_length=176)),
                ('PRZ_VEND', models.FloatField(default=0)),
                ('PVOF_ARR', models.FloatField(db_column='PVOF_ARR', default=0, verbose_name='Prezzo Offerta')),
            ],
            options={
                'verbose_name': 'Importa Articoli Promo',
                'verbose_name_plural': 'Importa Articoli Promo',
                'db_table': 'scaricopromo.importaarticolipromo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meccanica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(blank=True, default='', max_length=50)),
                ('descrizione', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Meccanica',
                'verbose_name_plural': 'Meccaniche',
                'db_table': 'scaricopromo.meccanica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MettereInTipoFron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CdArticolo', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Mettere TipoFron',
                'verbose_name_plural': 'Mettere TipoFron',
                'db_table': 'scaricopromo.metterein_tipofron',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(blank=True, default='', max_length=50)),
                ('descrizione', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo Sconto',
                'verbose_name_plural': 'Tipi Sconto',
                'db_table': 'scaricopromo.tiposconto',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='aggiornaattri',
            options={'managed': False, 'verbose_name': 'Aggiorna Attributo', 'verbose_name_plural': 'Aggiorna Attributi'},
        ),
        migrations.AlterModelOptions(
            name='apriattri',
            options={'managed': False, 'verbose_name': 'Apri Attributo', 'verbose_name_plural': 'Apri Attributi'},
        ),
        migrations.AlterModelOptions(
            name='chiudiattri',
            options={'managed': False, 'verbose_name': 'Chiudi Attributo', 'verbose_name_plural': 'Chiudi Attributi'},
        ),
        migrations.AlterModelOptions(
            name='mettereina',
            options={'managed': False, 'verbose_name': 'Mettere in A', 'verbose_name_plural': 'Mettere in A'},
        ),
        migrations.AlterModelOptions(
            name='mettereine',
            options={'managed': False, 'verbose_name': 'Mettere in E', 'verbose_name_plural': 'Mettere in E'},
        ),
        migrations.AlterModelOptions(
            name='mettereinf',
            options={'managed': False, 'verbose_name': 'Mettere in F', 'verbose_name_plural': 'Mettere in F'},
        ),
        migrations.AlterModelOptions(
            name='mettereini',
            options={'managed': False, 'verbose_name': 'Mettere in I', 'verbose_name_plural': 'Mettere in I'},
        ),
        migrations.AlterModelOptions(
            name='mettereink',
            options={'managed': False, 'verbose_name': 'Mettere in K', 'verbose_name_plural': 'Mettere in K'},
        ),
        migrations.AlterModelOptions(
            name='mettereins',
            options={'managed': False, 'verbose_name': 'Mettere in S', 'verbose_name_plural': 'Mettere in S'},
        ),
        migrations.AlterModelOptions(
            name='nonpossomettereina',
            options={'managed': False, 'verbose_name': 'Non posso mettere in A', 'verbose_name_plural': 'Non posso mettere in A'},
        ),
        migrations.AlterModelOptions(
            name='perexport',
            options={'managed': False, 'verbose_name': 'Export Promozione', 'verbose_name_plural': 'Export Promozioni'},
        ),
        migrations.AlterModelOptions(
            name='perexportstorico',
            options={'managed': False, 'verbose_name': 'Export Storico', 'verbose_name_plural': 'Export Storici'},
        ),
    ]
