# Generated by Django 5.2.10 on 2026-02-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('app_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permesso App Utente',
                'verbose_name_plural': 'Permessi App Utenti',
                'db_table': 'user_app_permissions',
                'ordering': ['username', 'app_name'],
                'unique_together': {('username', 'app_name')},
            },
        ),
    ]
