# Generated by Django 5.2.7 on 2026-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='V_RicevimentiGoldArtFo',
            fields=[
                ('data_aggio', models.CharField(db_column='DTAAGGIO', max_length=10, null=True)),
                ('data', models.CharField(db_column='DATA', max_length=10, null=True)),
                ('settore', models.CharField(db_column='SETTORE', max_length=50, null=True)),
                ('reparto', models.CharField(db_column='REPARTO', max_length=50, null=True)),
                ('cod_interno_ric', models.IntegerField(db_column='CODICE_INTERNO_RIC', primary_key=True, serialize=False)),
                ('cod_ext_ric', models.CharField(db_column='COD_EXT_RIC', max_length=13, null=True)),
                ('fornitore', models.CharField(db_column='FORNITORE', max_length=4000, null=True)),
                ('desc_forn', models.CharField(db_column='DESC_FORN', max_length=4000, null=True)),
                ('contr_comm', models.CharField(db_column='CONTRATTO_COMMERCIALE', max_length=4000, null=True)),
                ('codartfo', models.CharField(db_column='COD_ARTFO', max_length=20, null=True)),
                ('cod_art', models.CharField(db_column='COD_ARTICOLO', max_length=4000, null=True)),
                ('desc_art', models.CharField(db_column='DESCRIZIONE_ART', max_length=4000, null=True)),
                ('stato', models.CharField(db_column='STATO', max_length=8, null=True)),
                ('unita_misura', models.CharField(db_column='UNITA_MISURA', max_length=12, null=True)),
                ('quantita_ordinata', models.DecimalField(db_column='QUANTITA_ORDINATA', decimal_places=3, max_digits=10, null=True)),
                ('peso_ordinato', models.DecimalField(db_column='PESO_ORDINATO', decimal_places=3, max_digits=10, null=True)),
                ('quantita_ricevuta', models.DecimalField(db_column='QUANTITA_RICEVUTA', decimal_places=3, max_digits=9, null=True)),
                ('peso_ricevuto', models.DecimalField(db_column='PESO_RICEVUTO', decimal_places=3, max_digits=9, null=True)),
                ('prezzo_unitario', models.DecimalField(db_column='PREZZO_UNITARIO', decimal_places=5, max_digits=15, null=True)),
                ('tot_ricevuto', models.DecimalField(db_column='TOT_RICEVUTO', decimal_places=5, max_digits=18, null=True)),
                ('corsia', models.FloatField(db_column='CORSIA', null=True)),
                ('campata', models.FloatField(db_column='CAMPATA', null=True)),
                ('facing', models.FloatField(db_column='FACING', null=True)),
                ('pzxcart', models.FloatField(db_column='PZXCART', null=True)),
                ('giacenza_pdv', models.FloatField(db_column='GIACENZA_PDV', null=True)),
                ('sito', models.IntegerField(db_column='SITO', null=True)),
                ('ean', models.CharField(db_column='EAN', max_length=14, null=True)),
                ('eanprinc', models.IntegerField(db_column='EANPRINC', null=True)),
                ('tipo', models.IntegerField(db_column='TIPO', null=True)),
            ],
            options={
                'db_table': 'v_RicevimentiGoldArtFo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntrataMerciOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_interno_ric', models.IntegerField()),
                ('cod_art', models.CharField(default='', max_length=4000)),
                ('data_ricevimento_modificata', models.DateField()),
                ('utente', models.CharField(max_length=50, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('cod_interno_ric', 'cod_art')},
            },
        ),
    ]
