# Generated by Django 5.2.7 on 2026-08-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScansioneOrtofrutta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean_scansionato', models.CharField(max_length=20)),
                ('data_competenza', models.DateField()),
                ('codart', models.CharField(blank=True, default='', max_length=26)),
                ('peso_num', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('qta', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('gest', models.CharField(blank=True, default='', max_length=20)),
                ('utente', models.CharField(max_length=50)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ortofrutta_scansione',
            },
        ),
    ]
