# Generated by Django 5.2.7 on 2026-08-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortofrutta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ean',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('DTAAGGIO', models.CharField(blank=True, default='', max_length=20)),
                ('CODART', models.CharField(blank=True, db_index=True, default='', max_length=26)),
                ('DESCRART', models.CharField(blank=True, default='', max_length=255)),
                ('EAN', models.CharField(blank=True, default='', max_length=28)),
                ('EANA', models.CharField(blank=True, default='', max_length=38)),
                ('TIPO', models.FloatField(default=0)),
                ('PRINC', models.FloatField(default=0)),
                ('STEAN', models.FloatField(default=0)),
                ('DTAINI', models.CharField(blank=True, default='', max_length=20)),
                ('STAFINE', models.CharField(blank=True, default='', max_length=20)),
                ('GEST', models.CharField(blank=True, default='', max_length=255)),
                ('DataCreazione', models.DateTimeField(blank=True, null=True)),
                ('iva', models.FloatField(default=0)),
            ],
            options={
                'db_table': 't_t_ean1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListinoGiorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_competenza', models.DateField()),
                ('codart', models.CharField(max_length=26)),
                ('prezzo_listino', models.DecimalField(decimal_places=4, max_digits=10)),
                ('utente_inserimento', models.CharField(max_length=50)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ortofrutta_listino_giorno',
                'constraints': [models.UniqueConstraint(fields=('data_competenza', 'codart'), name='uniq_listino_giorno_articolo')],
            },
        ),
    ]
