# Generated by Django 5.2.7 on 2026-08-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortofrutta', '0002_ean_listinogiorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinogiorno',
            name='data_competenza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
