# Generated by Django 5.2.7 on 2026-08-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortofrutta', '0004_alter_listinogiorno_data_competenza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansioneortofrutta',
            name='fatturato',
            field=models.BooleanField(default=False),
        ),
    ]
