# Generated by ChatGPT for the Edicola module

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EdicolaPrincipale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sett", models.CharField(blank=True, max_length=50, null=True)),
                ("rep", models.CharField(blank=True, max_length=50, null=True)),
                ("srep", models.CharField(blank=True, max_length=50, null=True)),
                ("ccom", models.TextField(blank=True, null=True)),
                ("descc", models.TextField(blank=True, null=True)),
                ("codart", models.BigIntegerField(db_index=True)),
                ("descrart", models.TextField(blank=True, null=True)),
                ("eanprinc", models.IntegerField(blank=True, db_index=True, null=True)),
                ("tipoean", models.IntegerField(blank=True, null=True)),
                ("stato", models.CharField(blank=True, max_length=50, null=True)),
                ("prezzovend", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("giacenza_pdv", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("ean", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("dtaini", models.CharField(blank=True, max_length=50, null=True)),
                ("dtafine", models.CharField(blank=True, max_length=50, null=True)),
                ("dtaaggio", models.CharField(blank=True, max_length=50, null=True)),
                ("data", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "edicola_principale",
            },
        ),
        migrations.CreateModel(
            name="SalvaPrinc",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sett", models.CharField(blank=True, max_length=50, null=True)),
                ("rep", models.CharField(blank=True, max_length=50, null=True)),
                ("srep", models.CharField(blank=True, max_length=50, null=True)),
                ("ccom", models.TextField(blank=True, null=True)),
                ("descc", models.TextField(blank=True, null=True)),
                ("codart", models.BigIntegerField(db_index=True)),
                ("descrart", models.TextField(blank=True, null=True)),
                ("eanprinc", models.IntegerField(blank=True, db_index=True, null=True)),
                ("tipoean", models.IntegerField(blank=True, null=True)),
                ("stato", models.CharField(blank=True, max_length=50, null=True)),
                ("prezzovend", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("giacenza_pdv", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("ean", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("dtaini", models.CharField(blank=True, max_length=50, null=True)),
                ("dtafine", models.CharField(blank=True, max_length=50, null=True)),
                ("dtaaggio", models.CharField(blank=True, max_length=50, null=True)),
                ("data", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "edicola_salva_princ",
            },
        ),
        migrations.CreateModel(
            name="EdicolaLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(default="INFO", max_length=10)),
                ("message", models.TextField()),
                ("details", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "edicola_log",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="edicolaprincipale",
            index=models.Index(fields=["codart", "eanprinc"], name="edicola_pri_codart_1a1f0e_idx"),
        ),
        migrations.AddIndex(
            model_name="edicolaprincipale",
            index=models.Index(fields=["ean"], name="edicola_pri_ean_f8db25_idx"),
        ),
        migrations.AddIndex(
            model_name="salvaprinc",
            index=models.Index(fields=["codart"], name="edicola_sal_codart_0c2e43_idx"),
        ),
        migrations.AddIndex(
            model_name="salvaprinc",
            index=models.Index(fields=["ean"], name="edicola_sal_ean_6a114c_idx"),
        ),
    ]
