# Generated by Django 5.2.10 on 2026-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DettaglioBuono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField()),
                ('totale', models.DecimalField(decimal_places=2, help_text='Quantità × Taglio', max_digits=10)),
            ],
            options={
                'verbose_name': 'Dettaglio Buono',
                'verbose_name_plural': 'Dettagli Buoni',
                'db_table': 'welfare.dettaglio_buoni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailImportata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField()),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_address', models.CharField(blank=True, max_length=255)),
                ('destinatario', models.CharField(blank=True, max_length=255)),
                ('cc', models.CharField(blank=True, max_length=255)),
                ('bcc', models.CharField(blank=True, max_length=255)),
                ('ricevuto_il', models.DateTimeField()),
                ('oggetto', models.CharField(blank=True, max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=255)),
                ('html_body', models.TextField(blank=True)),
                ('elaborata', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Importata',
                'verbose_name_plural': 'Email Importate',
                'db_table': 'welfare.email_importate',
                'ordering': ['-ricevuto_il'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RichiestaProvvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField()),
                ('data_importazione', models.DateTimeField(auto_now_add=True)),
                ('data_lavorazione', models.DateTimeField(blank=True, null=True)),
                ('mittente', models.CharField(blank=True, max_length=255)),
                ('nome_mittente', models.CharField(blank=True, max_length=255)),
                ('nominativo', models.CharField(max_length=255)),
                ('num_richiesta', models.CharField(max_length=50)),
                ('valore_buono', models.CharField(blank=True, max_length=255)),
                ('qta_buono', models.CharField(blank=True, max_length=255)),
                ('totale_buono', models.CharField(blank=True, max_length=255)),
                ('stato', models.CharField(default='PRONTO', max_length=255)),
                ('data_consegna', models.DateTimeField(blank=True, null=True)),
                ('emettitore', models.CharField(blank=True, max_length=255)),
                ('processato', models.BooleanField(default=False)),
                ('errore', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Richiesta Provvisoria',
                'verbose_name_plural': 'Richieste Provvisorie',
                'db_table': 'welfare.richieste_provvisorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RichiestaWelfare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(help_text='Data/ora ricezione email originale')),
                ('data_importazione', models.DateTimeField(auto_now_add=True, help_text='Data/ora import nel sistema')),
                ('data_lavorazione', models.DateTimeField(blank=True, help_text='Data/ora elaborazione', null=True)),
                ('data_consegna', models.DateTimeField(blank=True, help_text='Data/ora consegna al cliente', null=True)),
                ('num_richiesta', models.CharField(db_index=True, help_text='Codice richiesta Eudaimon (es. 00577148)', max_length=50, unique=True)),
                ('mittente', models.CharField(blank=True, help_text='Email mittente', max_length=255)),
                ('nome_mittente', models.CharField(blank=True, help_text='Nome azienda richiedente', max_length=255)),
                ('nominativo', models.CharField(help_text='Nome dipendente beneficiario', max_length=255)),
                ('emettitore', models.CharField(blank=True, max_length=255)),
                ('valore_buono', models.DecimalField(decimal_places=2, help_text='Taglio singolo buono (€)', max_digits=10)),
                ('qta_buono', models.IntegerField(help_text='Quantità buoni richiesti')),
                ('totale_buono', models.DecimalField(decimal_places=2, help_text='Importo totale (€)', max_digits=10)),
                ('stato', models.CharField(choices=[('PRONTO', 'Pronto'), ('ELABORATO', 'Elaborato'), ('CONSEGNATO', 'Consegnato'), ('INEVASO', 'Inevaso')], db_index=True, default='PRONTO', max_length=50)),
                ('utente_preparazione', models.CharField(blank=True, help_text='Username operatore preparazione', max_length=30)),
                ('utente_consegna', models.CharField(blank=True, help_text='Username operatore consegna', max_length=30)),
                ('controllo', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Richiesta Welfare',
                'verbose_name_plural': 'Richieste Welfare',
                'db_table': 'welfare.richieste',
                'ordering': ['-data_creazione'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ruolo', models.IntegerField(choices=[(1, 'Front-Office'), (2, 'Ufficio Cassa'), (3, 'Contabilità'), (99, 'Administrator')], unique=True)),
                ('descrizione', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ruolo',
                'verbose_name_plural': 'Ruoli',
                'db_table': 'welfare.ruoli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaglioBuono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_nominale', models.IntegerField(unique=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Taglio Buono',
                'verbose_name_plural': 'Tagli Buono',
                'db_table': 'welfare.tagli_buono',
                'ordering': ['valore_nominale'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('data_login', models.DateTimeField(blank=True, null=True)),
                ('volte', models.IntegerField(default=0, help_text='Contatore accessi')),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
                'db_table': 'welfare.utenti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificaEudaimon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_richiesta', models.CharField(max_length=255)),
                ('valore_buono', models.CharField(blank=True, max_length=255)),
                ('quantita', models.FloatField(blank=True, null=True)),
                ('importo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nominativo_dipendente', models.CharField(blank=True, max_length=255)),
                ('nome_account', models.CharField(blank=True, max_length=255)),
                ('stato', models.CharField(blank=True, max_length=255)),
                ('data_ora_apertura', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Verifica Eudaimon',
                'verbose_name_plural': 'Verifiche Eudaimon',
                'db_table': 'welfare.verifica_eudaimon',
                'managed': False,
            },
        ),
    ]
